### ISSUE TITLE
Error 500 after installation

### ISSUE THREAD

**Issue by AaronTajriba** [SIELOnline/Acumulus-for-PrestaShop#4]
So i finally was able to install this module on a fresh install of prestashop; but the next error occured right after installation on the configuration page.
![Scherm­afbeelding 2023-01-17 om 11 49 53](https://user-images.githubusercontent.com/70962249/212880030-75b7ab3a-98b9-4265-bdc3-4737b0a32996.png)
With debug;
![Scherm­afbeelding 2023-01-17 om 11 50 22](https://user-images.githubusercontent.com/70962249/212880134-98984533-1d1f-4f2b-8e16-b6dd69e469df.png)
Our shop is in the following configuration
PS 1.7.8.7
PHP 7.4
MODULE: 7.5.0

**Comment by AaronTajriba** [comment]
@fietserwin Why is this issue closed? This issue prevents us from using this module and using Acumulus

**Comment by fietserwin** [comment]
Thanks for reporting, will be solved in version 7.6.1 (of libAcumulus).

I am moving all code to much stronger PHP 7.4 typing (typed properties, void return type) and am using strict_types=1 almost everywhere now. This bug is a typical example of a missed error during testing as it only occurs on new installs (when no configuration for the module has been stored yet).  As it happens, I am testing PS now, hoping that 8.0 indeed will allow the use of PHP 8.x. Version 7.6.1 of this PrestaShop module will be released in a few days

**Comment by AaronTajriba** [comment]
Hi @fietserwin Thanks for your reply, is there any indication of when the module will be released? We need it before the start of the next week.

**Comment by fietserwin** [comment]
I wanted to wait with the release a little longer, as to test a bit more and to incorporate support for OpenCart 4. However, the latter takes more time than expected. To let you continue your work, I released a version 7.6.1 only for PrestaShop:  download it from https://forum.acumulus.nl/index.php/topic,2745.msg15312.html
